{
	"service_name": "get_contests_of_league",
	"message": "",
	"global_error": "",
	"error": [],
	"data": {
		"offset": 20,
		"sort_field": "season_scheduled_date",
		"sort_order": "DESC",
		"contest_list": [
			{
				"contest_id": "10",
				"league_id": "113",
				"invite_id": "2",
				"invite_from": "9",
				"contest_name": "",
				"collection_master_id": "5",
				"contest_unique_id": "2rnpHLsWw",
				"entry_fee": "15",
				"size": "0",
				"minimum_size": "0",
				"season_scheduled_date": "2017-09-02 19:30:00",
				"total_user_joined": "0",
				"user_id": "9",
				"season_game_uid": "",
				"multiple_lineup": "1",
				"contest_access_type": "1",
				"user_joined_count": "0",
				"contest_date": "2017-09-02 19:30:00",
				"start_week": null,
				"end_week": null,
				"league_type": "1",
				"conference_id": "2",
				"team_league_id": "128",
				"player_position": "CB",
				"category_name": "Most Interceptions",
				"question": "How many interceptions will {{player_position}} have?",
				"que_category_type": "7",
				"game_starts_in": 1504360800000,
				"today": 1503651600000,
				"current_timestamp": 1503651600,
				"scheduled_timestamp": 1504360800,
				"end": 709200000,
				"invite_from_username": "vinfo9"
			},
			{
				"contest_id": "9",
				"league_id": "113",
				"invite_id": null,
				"invite_from": null,
				"contest_name": "",
				"collection_master_id": "5",
				"contest_unique_id": "3zVbTjo0Y",
				"entry_fee": "10",
				"size": "0",
				"minimum_size": "0",
				"season_scheduled_date": "2017-09-02 19:30:00",
				"total_user_joined": "0",
				"user_id": "8",
				"season_game_uid": "",
				"multiple_lineup": "1",
				"contest_access_type": "0",
				"user_joined_count": "0",
				"contest_date": "2017-09-02 19:30:00",
				"start_week": null,
				"end_week": null,
				"league_type": "1",
				"conference_id": "2",
				"team_league_id": "128",
				"player_position": "CB",
				"category_name": "Most Interceptions",
				"question": "How many interceptions will {{player_position}} have?",
				"que_category_type": "7",
				"game_starts_in": 1504360800000,
				"today": 1503651600000,
				"current_timestamp": 1503651600,
				"scheduled_timestamp": 1504360800,
				"end": 709200000
			},
 		],
		"total": "4",
		"is_load_more": false
	},
	"response_code": 200
}
